# Paths to the folders to be used for encoding
# realpath will be used automatically, but using absolute paths is recommended
#
# IMPORTANT: IZUMI WILL NOT VALIDATE THIS YAML FILE

# Type of Izumi running (downloader or encoder)
#type: "downloader"
type: "encoder"

folders:
    # The directory in which new files will be made in by ruTorrent or the flask server
    watch: "/home/rocia/Videos/Incoming"

    # Where a copy of the mkv video will be made
    mkv: "/home/rocia/Videos/MKV"

    # Where the hardsub mp4 will be made
    # mp4: "/home/rocia/Videos/Nyaa4"
    mp4: "/home/rocia/Videos/MP4"

    # A temporary directory used to store a copy of the mkv.
    # This temp directory may NOT contain the single quote.
    temp: "../../Videos/temp"

    # A temporary "hard" directory used by the encoders to temporarily store the new file
    # before hardlinking it to the watch directory. We do this because the system assumes
    # the file is already done downloading
    hard: "/home/rocia/Videos/hard"

sync:
    # rclone folder to upload all show/ep.mkv to
    # Note: We are going to assume that rclone is already installed on the host sytsem,
    # as destinations are typically personal and should not be with the application
    # ffmpeg and ffmpeg-10bit are included as they are standalone
    mkv:
        priority: ['sanka-kan:Airing']
        regular: ['carmilla-wizo:Airing', 'weebrary:Airing']
        encoders: 
                x264: ['http://izumi.best.moe:1400']
                x265: ['http://sakura.wizo.sh:9695']
                status_code: 209
                fallback: yes
    mp4:
        # If this is encoder, be careful to only add the destinations you want
        priority: ['sanka-kan:Airing [Hardsub]']
        regular: ['carmilla-wizo:Airing [Hardsub]']
        downloaders: ['http://ananke.feralhosting.com:5932']

    mp4-distribution:
        # Distributors are URLs that will be posted
        distributors:
            # For sequential distributors, they will be tried until one succeeds
            sequential: ['http://ananke.feralhosting.com:5932']
            # For always distributors, these will always be notified regardless
            always: []

        # While the others are for specifying where to send distribution requests
        # This species for the distributor where to source and where to target
        distribution:
                # Element 0: Source, element n >= 1: All destinations to target
                - ["sanka-kan:Airing [Hardsub]", "carmilla-wizo:Airing [Hardsub]"]
                - ["carmilla-wizo:Airing [Hardsub]", "weebrary:Airing [Hardsub]", "badclone:Airing [Hardsub]"]

        # Settings for if am an encoder
        encoder:
            port: 1400
            source: 'kan:Anime/Airing'

notifications:
   upload:
        mkv:
            name: "Airing"
            urls: ['https://on.aeri.jp/post', 'https://badurl.asdfsa.com']
        mp4:
            name: "Airing [Hardsub]"
            urls: ['https://on.aeri.jp/post', 'https://badurl.asdfsa.com']

ffmpeg:
    threads: 6

sys:
    delimiter: "||"
