# You can optionally load a global config from a web source.
# If you do not, leave this as an empty string.
# [type: String-URL]
web-config: ""

# This is the folder the application will watch for new files. 
# [type: String-URL]
watch-folder: ""

# Grouping body to list endpoints for other Izumi modules for this app to talk to.
endpoints:

  # A list of U2 Encoder endpoints to send to.
  # Usually only one is here, but multiple encoder endpoints are supported (for various settings)
  # The format is a list of lists. Either list format is usable.
  # For each member in the list:
  # - Index 0 is the URL of the Encoding Unit (U2). It should include http/https. [type: String-URL]
  # - Index 1 is a an optional Authorization header token if the endpoint requires a header. [type: String-Key]
  # To have no encoders, simply have an empty list "[]"
  encoders:

    # These urls will always be notified, regardless if one fails
    always:
      - ["https://endpoint1.url/notify", "authorization_key"]
      - ["https://endpoint2.url/notify"]

    # Per each group in the list, each member in the group will be pinged
    # until one is successful.
    sequential:
      - - ["https://endpoint1.url/notify", "authorization_key"]
        - ['https://endpoint2.url/notify']
      - - ["https://endpoint3.url/notify", "authorization_key"]
        - ['https://endpoint4.url/notify']

  # A list of U3 Notification endpoints to send to.
  # The format is a list of lists. Either list format is usable.
  # For each member in the list:
  # - Index 0 is the URL of the Notification Unit (U3). It should include http/https. [type: String-URL]
  # - Index 1 is a an optional Authorization header token if the endpoint requires a header. [type: String-Key]
  # To have no notifiers, simply have an empty list "[]"
  notifiers:

    # These urls will always be notified, regardless if one fails
    always:
      - ["https://endpoint1.url/notify", "authorization_key"]
      - ["https://endpoint2.url/notify"]

    # Per each group in the list, each member in the group will be pinged
    # until one is successful.
    sequential:
      - - ["https://endpoint1.url/notify", "authorization_key"]
        - ['https://endpoint2.url/notify']
      - - ["https://endpoint3.url/notify", "authorization_key"]
        - ['https://endpoint4.url/notify']

  # A list of U4 Distributor endpoints to send to.
  # The format is a list of lists. Either list format is usable.
  # For each member in the list:
  # - Index 0 is the URL of the Distributor Unit (U4). It should include http/https. [type: String-URL]
  # - Index 1 is a an optional Authorization header token if the endpoint requires a header. [type: String-Key]
  # To have no distributors, simply have an empty list "[]"
  distributors:

    # These urls will always be notified, regardless if one fails
    always:
      - ["https://endpoint1.url/notify", "authorization_key"]
      - ["https://endpoint2.url/notify"]

    # Per each group in the list, each member in the group will be pinged
    # until one is successful.
    sequential:
      - - ["https://endpoint1.url/notify", "authorization_key"]
        - ['https://endpoint2.url/notify']
      - - ["https://endpoint3.url/notify", "authorization_key"]
        - ['https://endpoint4.url/notify']


# Application-specific settings
system:

  # This is the delimiter used by inotify to split the arguments.
  # Don't edit this unless you know what you're doing.
  # [type: String]
  delimiter: "||"

  # Whether or not the application should print more information.
  # [type: Boolean]
  verbose: Yes